name: diasporacare
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  country_picker: ^2.0.17
  flutter_otp_text_field: ^1.1.1
  multiselect: ^0.0.7
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  # shared_preferences: ^0.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.2.0
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/josefin-sans/JosefinSans-Bold.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-BoldItalic.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-Italic.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-Light.ttf 
        - asset: assets/fonts/josefin-sans/JosefinSans-LightItalic.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-SemiBold.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-SemiBoldItalic.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-Thin.ttf
        - asset: assets/fonts/josefin-sans/JosefinSans-ThinItalic.ttf
