name: diasporacare
description: A new Flutter project.


publish_to: 'none' 


version: 1.7.0+7

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_otp_text_field: ^1.1.1
  multiselect: ^0.0.7
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  intl: ^0.17.0
  jiffy: ^5.0.0
  shimmer: ^2.0.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.11.0
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0

  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/diaspologo.jpeg"

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/google_fonts/Poppins-Black.ttf
        - asset: assets/fonts/google_fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Bold.ttf
        - asset: assets/fonts/google_fonts/Poppins-BoldItalic.ttf 
        - asset: assets/fonts/google_fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/google_fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Extralight.ttf
        - asset: assets/fonts/google_fonts/Poppins-ExtralightItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Italic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Light.ttf
        - asset: assets/fonts/google_fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Medium.ttf
        - asset: assets/fonts/google_fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Regular.ttf
        - asset: assets/fonts/google_fonts/Poppins-Semibold.ttf
        - asset: assets/fonts/google_fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/google_fonts/Poppins-Thin.ttf
        - asset: assets/fonts/google_fonts/Poppins-ThinItalic.ttf
